language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: SRZrOSYMeX9xrFch6zD3y42X5lAbbEqm3AucIc6WhFH2ogzoQygj8hAY+GypbiTUDGUQ9P1bPrr7nSZMcJmlwxJV6iYudGNWrDbw2JEDL6RD8IBzmmsGDcVKRiQWdbg8tCJvPGriF/+OhkTxYCZRLxwLueXlAYMTvbJFjPn0CA6tCr077bs2GsvKyNMATE6JIol4sWNpN+h5jzDoTyrF70Tf6HzyD3c3qXp+REj7deZcJ/uHJqg8AP9q1YTrzzdFKLECTXBM9RuhAe3eQoWgo83ke7MTmWaKTq82L0GRf2I6VMRYLBOUwA2LqWIbJ37Tc/V+mpR9gtv+hDFicth/S5cSpf2u33pZjjk3TCLgVrIqWaGpT899ttZMlQc+EBs8Ilh6Td4CDDI2opbX4/BXuwHPHXD84DiALUysIH/9Sfcg72IW2G6Mwt7jhOh2JDiMhjzBRegT3ruZpdEOMNUgWMIlJj5ZTpuXb37DJVYB33vJZ0GcBCN96Ik1bUdLkRBtrg0eccCVU299HQ1nEPCLMUgz7d1G4YPKifjl46dTdCw93f7dLqa5/XVFQLczjxunaZMs3TWONebVbMWF21H2BqejbNhDZdRF9w2lf2HLK5FphPmFw02jEwFlDj/KPfrzkJSYfpzjFFotJz4SpiXRMplOfJlhk4iT5OM7HAdNFk8=
  app: peaceful-island-82409
